services:
  mongo:
    image: mongo
    restart: always
    containerName: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=Reviews
    volumes:
      -

  web:
    build: .
    ports:
      - 80:3000
